// VEX Academy Curriculum — Part 1: Units 1-3 (Módulos 1-38)
const CURRICULUM_P1 = [
// ======================
// UNIDAD 1: INTRODUCCIÓN Y CONFIGURACIÓN (10 módulos)
// ======================
{id:1,unit:1,unitTitle:'Introducción y Configuración',title:'Instalación de VS Code y Extensiones VEX',level:'Básico',type:'lesson',free:true,duration:25,
desc:'Configura tu entorno profesional con VS Code y las extensiones oficiales de VEX Robotics.',
theory:`<h3>Herramientas Necesarias</h3><ul><li><strong>Visual Studio Code</strong> — Editor principal (code.visualstudio.com)</li><li><strong>Extensión VEX Robotics</strong> — Busca en el Marketplace de VS Code</li><li><strong>C/C++ Extension Pack</strong> — De Microsoft para IntelliSense</li></ul><h3>Crear tu Primer Proyecto</h3><p>Abre <code>Ctrl+Shift+P</code> → "VEX: New Project" → Selecciona <strong>C++ VEXcode Pro</strong>. Todo el código de competencia se escribe aquí.</p>`,
code:`#include "vex.h"\nusing namespace vex;\nbrain Brain;\nmotor MotorIzq = motor(PORT1, ratio18_1, false);\nmotor MotorDer = motor(PORT10, ratio18_1, true);\nint main() {\n    MotorIzq.spin(fwd, 50, pct);\n    MotorDer.spin(fwd, 50, pct);\n    wait(2, sec);\n    MotorIzq.stop(); MotorDer.stop();\n}`,
api_ref:'vex::motor, vex::brain', exercise:'Crea un proyecto C++, compila sin errores y muestra "Hola VEX" en el Brain Screen.'},

{id:2,unit:1,unitTitle:'Introducción y Configuración',title:'Estructura del Proyecto y Archivo vex.h',level:'Básico',type:'lesson',free:true,duration:25,
desc:'Entiende la arquitectura de un proyecto VEXcode Pro y qué está incluido en vex.h.',
theory:`<h3>Estructura del Proyecto</h3><pre>mi-robot/\n├── include/\n│   ├── vex.h          ← Headers de VEX\n│   └── robot-config.h ← Configuración de dispositivos\n└── src/\n    ├── robot-config.cpp\n    ├── auton.cpp\n    └── main.cpp</pre><p>El namespace <code>vex::</code> contiene todas las clases: motor, brain, inertial, distance, etc. Usar <code>using namespace vex;</code> evita escribir el prefijo cada vez.</p>`,
code:`// robot-config.h — TODA la configuración va aquí\n#include "vex.h"\nextern brain    Brain;\nextern motor    MotorIzq;\nextern motor    MotorDer;\nextern inertial Imu;\n// robot-config.cpp\nbrain    Brain;\nmotor    MotorIzq = motor(PORT1,  ratio18_1, false);\nmotor    MotorDer = motor(PORT10, ratio18_1, true);\ninertial Imu     = inertial(PORT7);`,
api_ref:'vex::brain, namespace vex', exercise:'Organiza tu proyecto moviendo todos los devices a robot-config.h. Verifica que main.cpp compila incluyendo el header.'},

{id:3,unit:1,unitTitle:'Introducción y Configuración',title:'Actualización de Firmware y Gestión de Slots',level:'Básico',type:'lesson',free:true,duration:20,
desc:'Mantén el Brain V5 actualizado y administra los 8 slots de programa.',
theory:`<h3>Firmware Update</h3><p>Conecta el Brain V5 por USB → VS Code detectará si hay una actualización. Ve a la barra lateral VEX → "Brain Firmware" → Update All. Un firmware desactualizado puede causar comportamientos inesperados en competencia.</p><h3>Slots de Programa</h3><p>El Brain V5 almacena hasta <strong>8 programas</strong> simultáneos. Asigna el slot 1 a tu autónomo principal, slot 2 al autónomo de respaldo y slots 3-4 a programas de calibración.</p>`,
code:`// Seleccionar slot de descarga en VS Code:\n// 1. Clic en el ícono VEX en la barra lateral\n// 2. Selecciona "Slot 1" antes de descargar\n// 3. En el Brain: Programs → Slot 1\n// Buen hábito: Nombra cada slot descriptivamente\n// Slot 1: AUTON_PRINCIPAL\n// Slot 2: AUTON_RESPALDO  \n// Slot 3: CALIBRACION`,
api_ref:'VEX Brain Firmware Updater', exercise:'Actualiza el firmware de tu Brain y todos los Smart Motors. Descarga tu proyecto en el Slot 1. Verifica que ejecuta correctamente.'},

{id:4,unit:1,unitTitle:'Introducción y Configuración',title:'Tipos de Datos C++ para Robótica',level:'Básico',type:'lesson',free:true,duration:30,
desc:'Domina los tipos de datos esenciales y las unidades de medida en VEX C++.',
theory:`<h3>Tipos Comunes</h3><ul><li><code>double</code> — Para velocidades, ángulos, distancias (mayor precisión)</li><li><code>int</code> — Contadores, enumeraciones de estado</li><li><code>bool</code> — Flags de control true/false</li><li><code>void</code> — Funciones que no retornan valor</li></ul><h3>Unidades VEX</h3><p>La API acepta: <code>pct</code> (%), <code>rpm</code>, <code>degrees</code>, <code>rotations</code>, <code>mm</code>, <code>inches</code>, <code>cm</code>, <code>sec</code>, <code>msec</code>.</p>`,
code:`double velocidad = 75.5;    // porcentaje\ndouble angulo    = 90.0;    // grados\nbool   enMarcha  = true;\nint    contPiezas = 0;\n// Constantes importantes\nconst double KP = 0.8;  // PID proporcional\nconst double KI = 0.001;\nconst double KD = 4.0;\n// Conversión de unidades\ndouble rad = angulo * M_PI / 180.0; // grados a radianes`,
api_ref:'vex_units.h — distanceUnits, rotationUnits, timeUnits, velocityUnits', exercise:'Declara variables para: velocidad del robot (pct), ángulo IMU (degrees), tiempo de autónomo (sec). Imprime cada una en el Brain Screen.'},

{id:5,unit:1,unitTitle:'Introducción y Configuración',title:'Git y GitHub para Equipos VEX',level:'Básico',type:'lesson',free:true,duration:30,
desc:'Control de versiones profesional para tu equipo. Los jueces valoran el historial de commits.',
theory:`<h3>Por qué GitHub en Competencia</h3><p>Un repositorio con commits fechados es evidencia irrefutable del proceso de ingeniería. Difícil de falsificar. Los jueces del <strong>Excellence Award</strong> y <strong>Design Award</strong> lo reconocen.</p><h3>Flujo de Trabajo</h3><p>Usa la rama <code>main</code> para código probado. <code>dev</code> para experimentar. Haz un commit descriptivo por cada sesión.</p>`,
code:`# Flujo esencial de Git para VEX\ngit init\ngit add .\ngit commit -m "feat: añadir PID de giro con IMU"\ngit branch dev      # rama de experimentos\ngit checkout dev\n# ...probar código nuevo...\ngit checkout main\ngit merge dev       # fusionar cuando funcione\ngit push origin main`,
api_ref:'git — control de versiones', exercise:'Crea un repo en GitHub para tu equipo. Escribe un README.md con: nombre del equipo, robot, sensores usados y lista de premios. Haz el primer commit.'},

{id:6,unit:1,unitTitle:'Introducción y Configuración',title:'Brain Screen — Pantalla Táctil y Visualización',level:'Básico',type:'lesson',free:true,duration:25,
desc:'Usa la pantalla del Brain V5 para debug en tiempo real y dashboards de competencia.',
theory:`<h3>Clase brain::lcd</h3><p>La pantalla del Brain es 480×272 píxeles. Puedes dibujar texto, formas y usar toques para interacción. Es tu principal herramienta de diagnóstico en el piso de competencia.</p><h3>Usos en Competencia</h3><ul><li>Mostrar valores del IMU en tiempo real</li><li>Dashboard de temperatura de motores</li><li>Selector de autónomo con toque</li><li>Alertas de batería baja</li></ul>`,
code:`brain Brain;\nint main() {\n    Brain.Screen.setFont(mono20);\n    Brain.Screen.setPenColor(red);\n    Brain.Screen.printAt(10, 40, "TEMP: %.1f C",\n        Motor1.temperature(celsius));\n    // Detectar toque\n    if (Brain.Screen.pressing()) {\n        int x = Brain.Screen.xPosition();\n        int y = Brain.Screen.yPosition();\n        Brain.Screen.printAt(10,80,"Toque: %d,%d",x,y);\n    }\n    // Dibujar formas\n    Brain.Screen.drawRectangle(10,100,200,50);\n    Brain.Screen.drawCircle(400,136,30);\n}`,
api_ref:'vex::brain — screen.printAt(), screen.pressing(), screen.drawRectangle(), screen.setFont()', exercise:'Crea un dashboard que muestre en tiempo real: heading del IMU, temperatura de 2 motores, y nivel de batería del Brain. Actualiza cada 100ms.'},

{id:7,unit:1,unitTitle:'Introducción y Configuración',title:'Batería y Timer del Brain',level:'Básico',type:'lesson',free:true,duration:20,
desc:'Monitorea la batería en tiempo real y gestiona el tiempo de tu autónomo.',
theory:`<h3>Monitoreo de Batería</h3><p>Una batería por debajo del 50% puede causar que los motores no alcancen la velocidad objetivo, arruinando la precisión del PID. Siempre verifica antes de competir.</p><h3>Timer del Brain</h3><p>Usa <code>Brain.Timer</code> para medir tiempos de ejecución, limitar fases del autónomo y crear timeouts de seguridad.</p>`,
code:`// Batería\ndouble pct_bat = Brain.Battery.capacity(pct);\ndouble volt    = Brain.Battery.voltage(volt);\ndouble curr    = Brain.Battery.current(amp);\nBrain.Screen.printAt(10,40,"Batería: %.0f%%", pct_bat);\nif (pct_bat < 50) { /* ALERTA */ }\n// Timer\nBrain.Timer.reset();\n// ...código del autónomo...\nwhile(Brain.Timer.time(sec) < 14.5) {\n    // dentro del límite de 15s\n}`,
api_ref:'vex::brain::battery — capacity(), voltage(), current() | brain::timer — reset(), time(sec)', exercise:'Programa un autónomo con timeout de seguridad: si tarda más de 14.5 segundos, detén todos los motores automáticamente.'},

{id:8,unit:1,unitTitle:'Introducción y Configuración',title:'Altavoz del Brain — Alertas Sonoras',level:'Básico',type:'lesson',free:true,duration:15,
desc:'Usa el altavoz interno para alertas de estado durante competencia.',
theory:`<h3>Cuándo Usar el Altavoz</h3><ul><li>Confirmar calibración del IMU completada</li><li>Alerta de temperatura alta de motor</li><li>Señal de inicio/fin del autónomo</li><li>Error de sensor detectado</li></ul><p>En el piso de competencia hay mucho ruido, usa sonidos cortos y distintos para cada evento.</p>`,
code:`brain Brain;\nvoid alertaLista() {\n    Brain.Screen.printAt(10,40,"Sistemas listos!");\n    // Sonido de confirmación\n    // Nota: El Brain V5 tiene salida de audio integrada\n    wait(200, msec);\n}\nvoid alertaTemp(motor m) {\n    if (m.temperature(celsius) > 55) {\n        Brain.Screen.setPenColor(red);\n        Brain.Screen.printAt(10,70,"¡MOTOR CALIENTE!");\n    }\n}`,
api_ref:'vex::brain — speaker (sin API directa, usar wait + pantalla)', exercise:'Crea un sistema de alertas visuales: verde cuando el IMU calibra, rojo cuando un motor supera 55°C, amarillo cuando la batería baja de 50%.'},

{id:9,unit:1,unitTitle:'Introducción y Configuración',title:'Mejores Prácticas de Código en VEX',level:'Básico',type:'lesson',free:true,duration:30,
desc:'Escribe código limpio, mantenible y que los jueces puedan entender en una entrevista.',
theory:`<h3>Reglas de Oro</h3><ul><li><strong>Nombres descriptivos</strong>: <code>velocidadMaxima</code> no <code>vm</code></li><li><strong>Constantes en mayúsculas</strong>: <code>const double KP_GIRO = 0.8;</code></li><li><strong>Una función = una responsabilidad</strong>: <code>girarA()</code> solo gira, no avanza</li><li><strong>Comenta el POR QUÉ</strong>: no el qué (el código ya lo dice)</li></ul><h3>Estructura para Competencia</h3><p>Separa: <code>pre_auton()</code> → calibración, <code>autonomous()</code> → puntaje, <code>usercontrol()</code> → control del piloto.</p>`,
code:`// MAL — difícil de mantener\nmotor m=motor(PORT1,ratio18_1,false);\nvoid f(){m.spin(fwd,x,pct);}\n// BIEN — código de competencia profesional\nconst double VEL_AUTON = 70.0; // % — calibrado 2024-03-10\nmotor MotorTraccionIzq = motor(PORT1, ratio18_1, false);\n// Gira el robot al ángulo dado usando IMU (control P)\nvoid girarA(double grados_objetivo) {\n    // implementación...\n}`,
api_ref:'Estándares de código VEX', exercise:'Refactoriza tu código del autónomo anterior. Agrega comentarios al estilo de documentación para cada función. Asegúrate que alguien más en tu equipo pueda entenderlo sin ayuda.'},

{id:10,unit:1,unitTitle:'Introducción y Configuración',title:'Examen Unidad 1 — Configuración',level:'Básico',type:'exam',free:true,duration:15,
desc:'Verifica tu comprensión de entorno, C++ y GitHub para VEX V5.',exam:[
{q:'¿Cuál es la plantilla de proyecto correcta para programación avanzada?',options:['Bloques','Python','C++ VEXcode Pro','JavaScript'],correct:2},
{q:'¿Dónde debe ir la declaración de todos los dispositivos del robot?',options:['main.cpp','robot-config.h','makefile','vex.h'],correct:1},
{q:'¿Qué unidad usa la API para medir ángulos de motores?',options:['radianes','grados (degrees)','revoluciones por minuto','metros'],correct:1},
{q:'¿Qué rama de Git debe contener el código estable para competencia?',options:['dev','experimental','feature','main'],correct:3},
{q:'¿Cuántos slots de programa tiene el Brain V5?',options:['4','6','8','12'],correct:2},
],code:'',api_ref:''},

// ======================
// UNIDAD 2: EL CEREBRO (BRAIN) Y SISTEMA (10 módulos)
// ======================
{id:11,unit:2,unitTitle:'El Cerebro (Brain) V5',title:'Clase brain — Visión General',level:'Básico',type:'lesson',free:true,duration:20,
desc:'El Brain V5 es el corazón del robot. Aprende su arquitectura de hardware y software.',
theory:`<h3>Hardware del Brain V5</h3><ul><li><strong>21 puertos inteligentes</strong> (Smart Ports) para motores y sensores</li><li><strong>8 puertos 3-wire</strong> para sensores legados</li><li><strong>Procesador ARM</strong> dual-core de 32 bits</li><li><strong>Pantalla táctil</strong> 480×272 px a color</li><li><strong>WiFi</strong> integrado para streaming y control</li></ul><h3>El Objeto Brain</h3><p>El objeto <code>Brain</code> agrupa acceso a Screen, Battery, Timer y ThreeWirePort.</p>`,
code:`#include "vex.h"\nusing namespace vex;\nbrain Brain;\nint main() {\n    // Propiedades del Brain\n    Brain.Screen.printAt(10,40,"Puertos: 21+8");\n    Brain.Screen.printAt(10,70,\n        "Batería: %.0f%%", Brain.Battery.capacity(pct));\n    Brain.Screen.printAt(10,100,\n        "Voltaje: %.2fV", Brain.Battery.voltage(volt));\n}`,
api_ref:'vex::brain — Screen, Battery, Timer, ThreeWirePort', exercise:'Crea un programa que muestre en el Brain Screen una pantalla de estado con batería, voltage y tiempo activo (usando Brain.Timer).'},

{id:12,unit:2,unitTitle:'El Cerebro (Brain) V5',title:'brain.screen — Dibujo y Texto Avanzado',level:'Básico',type:'lesson',free:true,duration:25,
desc:'Domina la API gráfica del Brain para crear dashboards y selectores de autónomo.',
theory:`<h3>Sistema de Coordenadas</h3><p>Origen (0,0) en la esquina superior izquierda. Ancho: 480px, Alto: 272px.</p><h3>Funciones Clave</h3><ul><li><code>printAt(x, y, formato, ...)</code> — Texto con formato printf</li><li><code>drawRectangle(x, y, w, h)</code> — Rectángulo</li><li><code>drawCircle(x, y, r)</code> — Círculo</li><li><code>setFillColor(color)</code> — Color de relleno</li><li><code>setFont(font)</code> — Tamaño de fuente</li></ul>`,
code:`brain Brain;\n// Selector de autónomos con toque\nint seleccionAuton = 0;\nvoid dibujarSelector() {\n    // Botón Autónomo 1\n    Brain.Screen.setFillColor(red);\n    Brain.Screen.drawRectangle(10,80,200,80);\n    Brain.Screen.setPenColor(white);\n    Brain.Screen.printAt(60,130,"AUTON A");\n    // Botón Autónomo 2\n    Brain.Screen.setFillColor(blue);\n    Brain.Screen.drawRectangle(270,80,200,80);\n    Brain.Screen.printAt(320,130,"AUTON B");\n}\nvoid checkTouch() {\n    if (Brain.Screen.pressing()) {\n        int x = Brain.Screen.xPosition();\n        seleccionAuton = (x < 240) ? 1 : 2;\n    }\n}`,
api_ref:'vex::brain — screen.printAt, drawRectangle, drawCircle, setFillColor, setFont, setPenColor', exercise:'Crea un selector de autónomo táctil con 3 opciones en la pantalla del Brain. El autónomo elegido debe ejecutar una estrategia diferente.'},

{id:13,unit:2,unitTitle:'El Cerebro (Brain) V5',title:'brain.battery — Monitoreo Eléctrico',level:'Básico',type:'lesson',free:true,duration:20,
desc:'Monitorea la salud eléctrica del robot para evitar fallas en competencia.',
theory:`<h3>Parámetros Clave</h3><ul><li><code>capacity(pct)</code> — Porcentaje de carga (0-100%)</li><li><code>voltage(volt)</code> — Voltaje actual (~12.8V llena)</li><li><code>current(amp)</code> — Corriente consumida total</li></ul><h3>Voltaje y Rendimiento</h3><p>A menos de 11V los motores pierden torque significativamente. El PID calibrado a 12.8V puede fallar con batería baja. Siempre compite con más del 70%.</p>`,
code:`brain Brain;\nvoid monitorearBateria() {\n    double pct  = Brain.Battery.capacity(pct);\n    double volt = Brain.Battery.voltage(volt);\n    double amp  = Brain.Battery.current(amp);\n    // Alerta visual\n    if (pct < 50) {\n        Brain.Screen.setFillColor(red);\n        Brain.Screen.setPenColor(white);\n        Brain.Screen.printAt(10,50,"¡BATERÍA BAJA: %.0f%%!", pct);\n    } else {\n        Brain.Screen.printAt(10,50,"Bat: %.0f%% %.2fV %.1fA",\n            pct, volt, amp);\n    }\n}`,
api_ref:'vex::brain::battery — capacity(pct), voltage(volt), current(amp)', exercise:'Implementa un sistema de alerta de batería que cambie el color del fondo del Brain Screen: verde >70%, amarillo 50-70%, rojo <50%.'},

{id:14,unit:2,unitTitle:'El Cerebro (Brain) V5',title:'brain.timer — Control de Tiempo de Ejecución',level:'Básico',type:'lesson',free:true,duration:20,
desc:'Gestiona el tiempo exacto de tu autónomo y crea timeouts de seguridad.',
theory:`<h3>Timer en Competencia</h3><p>VEX da exactamente 15 segundos de autónomo. Si el robot no para a tiempo, el árbitro puede descalificarte o el Field Control te cortará. Siempre implementa un timeout.</p><ul><li><code>Brain.Timer.reset()</code> — Reinicia a cero</li><li><code>Brain.Timer.time(sec)</code> — Tiempo transcurrido en segundos</li><li><code>Brain.Timer.time(msec)</code> — En milisegundos (más preciso)</li></ul>`,
code:`brain Brain;\nvoid autonomous() {\n    Brain.Timer.reset();\n    // TImeout de seguridad: detener todo a 14.5s\n    auto stopAll = [&]() {\n        MotorIzq.stop(); MotorDer.stop();\n    };\n    // Fase 1: Avanzar (máximo 4 segundos)\n    MotorIzq.spin(fwd,70,pct);\n    MotorDer.spin(fwd,70,pct);\n    while(Brain.Timer.time(sec) < 4.0) { wait(10,msec); }\n    stopAll();\n    // Continuar solo si hay tiempo suficiente\n    if (Brain.Timer.time(sec) < 13.0) {\n        // Fase 2...\n    }\n}`,
api_ref:'vex::brain::timer — reset(), time(sec), time(msec)', exercise:'Añade un timeout de 14.5 segundos a tu autónomo existente. Muestra el tiempo restante en el Brain Screen durante la ejecución.'},

{id:15,unit:2,unitTitle:'El Cerebro (Brain) V5',title:'Puertos 3-Wire y ThreeWirePort',level:'Intermedio',type:'lesson',free:false,duration:25,
desc:'Conecta sensores y actuadores legados a través del puerto 3-Wire del Brain.',
theory:`<h3>El Puerto 3-Wire</h3><p>El Brain V5 tiene 8 puertos 3-wire etiquetados A-H. Son compatibles con TODOS los sensores del sistema VEX IQ y VEX EDR legado.</p><h3>Dispositivos Compatible</h3><ul><li>Bumper Switch, Limit Switch</li><li>Line Follower, Light Sensor</li><li>Potentiometer, Shaft Encoder (Quad)</li><li>Sonar Sensor (Ultrasónico)</li><li>Actuadores neumáticos (digital_out)</li><li>Servos genéricos (pwm_out)</li></ul>`,
code:`brain Brain;\n// Declarar dispositivos 3-wire\nbumper  Bumper1 = bumper(Brain.ThreeWirePort.A);\nencoder Encoder1= encoder(Brain.ThreeWirePort.C); // C,D = par\npotentiometerV2 Pot = potentiometerV2(Brain.ThreeWirePort.G);\ndigital_out Solenoide = digital_out(Brain.ThreeWirePort.H);\nint main() {\n    bool presionado = Bumper1.pressing();\n    double angle = Pot.angle(degrees);\n    Solenoide.set(true); // activar neumático\n}`,
api_ref:'vex::brain — ThreeWirePort.A..H | bumper, potentiometerV2, digital_out, encoder', exercise:'Conecta un Bumper Switch al puerto A. Programa un loop que detenga los motores inmediatamente al presionarlo (botón de parada de emergencia).'},

{id:16,unit:2,unitTitle:'El Cerebro (Brain) V5',title:'Almacenamiento en Tarjeta SD',level:'Intermedio',type:'lesson',free:false,duration:25,
desc:'Guarda logs de competencia, configuraciones y datos de calibración en la SD del Brain.',
theory:`<h3>La SD en Competencia</h3><p>La tarjeta SD permite guardar datos entre sesiones. Casos de uso:</p><ul><li><strong>Logs de posición</strong>: Guardar la ruta del autónomo para análisis post-competencia</li><li><strong>Calibración persistente</strong>: Guardar offsets del IMU entre reiniciados</li><li><strong>Estadísticas</strong>: Puntaje por ronda, temperatura máxima</li></ul>`,
code:`brain Brain;\nvoid guardarLog(double x, double y, double heading) {\n    // Abrir archivo (crea si no existe)\n    FILE* f = fopen("/usd/robot_log.txt", "a");\n    if (f != nullptr) {\n        fprintf(f, "%.2f,%.2f,%.2f\\n", x, y, heading);\n        fclose(f);\n    }\n}\nvoid cargarConfig() {\n    FILE* f = fopen("/usd/config.txt", "r");\n    if (f != nullptr) {\n        double offset_imu;\n        fscanf(f, "%lf", &offset_imu);\n        fclose(f);\n    }\n}`,
api_ref:'fopen, fclose, fprintf, fscanf — POSIX file I/O en VEX', exercise:'Crea un logger que guarde en SD: timestamp, posición XY (si tienes odometría) y temperatura de los motores. Después de competir, analiza el log para identificar cuellos de botella.'},

{id:17,unit:2,unitTitle:'El Cerebro (Brain) V5',title:'Diagnóstico de Puertos Inteligentes',level:'Intermedio',type:'lesson',free:false,duration:20,
desc:'Detecta y maneja errores de conexión en tiempo real para evitar crashes en competencia.',
theory:`<h3>Estado de Puertos</h3><p>Un Smart Port puede estar: conectado, desconectado, en error, o con tipo incorrecto. Verificar el estado antes del autónomo previene crashes silenciosos donde el robot actúa como si el sensor existiera pero con valores de 0.</p>`,
code:`brain Brain;\nmotor  Motor1 = motor(PORT1, ratio18_1, false);\n// Verificar si el motor está conectado y funcionando\nvoid verificarSistemas() {\n    // Un motor instalado correctamente responde a velocity()\n    double rpm = Motor1.velocity(rpm);\n    // Si el port no está conectado, retorna 0 pero no falla\n    Brain.Screen.printAt(10,50,\n        "PORT1: %s", (Motor1.temperature(celsius) > 0) ?\n        "OK" : "REVISAR");\n    if (Brain.Battery.capacity(pct) < 70) {\n        Brain.Screen.printAt(10,80,"¡CARGAR BATERÍA!");\n    }\n}`,
api_ref:'vex::motor — temperature(), velocity() para verificar conexión', exercise:'Crea una rutina de diagnóstico pre-competencia que verifique 4 motores y 2 sensores. Si alguno falla, enciende la pantalla en rojo y beep visual antes de permitir el autónomo.'},

{id:18,unit:2,unitTitle:'El Cerebro (Brain) V5',title:'Manejo de Eventos con Callbacks',level:'Intermedio',type:'lesson',free:false,duration:30,
desc:'Programa reacciones instantáneas a eventos del sistema usando funciones callback.',
theory:`<h3>¿Qué es un Callback?</h3><p>Es una función que se ejecuta automáticamente cuando ocurre un evento. En VEX se usan para: botones del control presionados, toque en la pantalla, señales de competencia.</p><p>Son más eficientes que el polling (revisar en loop) porque no consumen CPU innecesariamente.</p>`,
code:`brain Brain;\ncontroller Control = controller(primary);\nbool intakeActivo = false;\n// Callback — se ejecuta AL MOMENTO que se presiona A\nvoid onBotonAPresionado() {\n    intakeActivo = !intakeActivo;  // toggle\n    // Activar/desactivar intake\n}\nint main() {\n    // Registrar callback\n    Control.ButtonA.pressed(onBotonAPresionado);\n    // Loop principal solo necesita manejar el drive\n    while(true) {\n        // Solo tracción aquí, el intake se maneja solo\n        int fwd = Control.Axis3.position();\n        int turn= Control.Axis1.position();\n        MotorIzq.spin(fwd, fwd+turn, pct);\n        MotorDer.spin(fwd, fwd-turn, pct);\n        wait(20, msec);\n    }\n}`,
api_ref:'vex::controller — ButtonA.pressed(), ButtonB.released() | vex::brain::screen — pressed()', exercise:'Implementa el control del intake de tu robot usando ÚNICAMENTE callbacks. No uses if(button.pressing()) en el loop principal.'},

{id:19,unit:2,unitTitle:'El Cerebro (Brain) V5',title:'Rendimiento: Ciclos de CPU y Timing',level:'Avanzado',type:'lesson',free:false,duration:25,
desc:'Optimiza los tiempos de ciclo para que tu robot responda con máxima precisión.',
theory:`<h3>La Regla del wait(20, msec)</h3><p>El procesador del Brain V5 corre a ~200MHz. Sin un delay mínimo por ciclo, el loop ocupa el 100% de CPU, calentando el sistema y causando comportamientos erráticos.</p><p><strong>Recomendación oficial VEX</strong>: siempre termina el loop con <code>wait(20, msec)</code> = 50Hz de actualización, suficiente para control preciso.</p><h3>Medir Tiempo de Ejecución</h3><p>Usa el Timer para medir cuánto tarda tu función de PID. Si supera 10ms, necesita optimización.</p>`,
code:`brain Brain;\nvoid loopControl() {\n    while(true) {\n        Brain.Timer.reset();\n        // === Tu código de control ===\n        double heading = Imu.heading(degrees);\n        // PID, odometría, etc.\n        double tiempoMs = Brain.Timer.time(msec);\n        Brain.Screen.printAt(10,200,\n            "Ciclo: %.1f ms", tiempoMs);\n        if (tiempoMs > 15) {\n            // ADVERTENCIA: ciclo muy largo\n        }\n        wait(20, msec); // 50Hz\n    }\n}`,
api_ref:'vex::brain::timer — time(msec) | wait(n, msec)', exercise:'Mide el tiempo de ciclo de tu loop de control. Identifica la función más lenta y optimízala. Objetivo: ciclo < 10ms para mantener 50Hz de control.'},

{id:20,unit:2,unitTitle:'El Cerebro (Brain) V5',title:'Examen Unidad 2 — El Brain V5',level:'Básico',type:'exam',free:false,duration:15,
desc:'Verifica tu dominio de la clase brain y sus subsistemas.',exam:[
{q:'¿Cuántos puertos inteligentes (Smart Ports) tiene el Brain V5?',options:['12','18','21','24'],correct:2},
{q:'¿Qué resolución tiene la pantalla táctil del Brain V5?',options:['320×240','480×272','640×400','800×480'],correct:1},
{q:'¿Cuándo se debe usar wait(20, msec) al final del loop?',options:['Solo si el robot no responde','Nunca, desperdicia tiempo','Siempre, para liberar CPU y mantener 50Hz','Solo durante el autónomo'],correct:2},
{q:'¿Qué retorna Brain.Battery.capacity(pct) para una batería bien cargada?',options:['12.8','1.0','100','200'],correct:2},
{q:'¿Cuál es la diferencia entre polling y callback para botones?',options:['No hay diferencia','El callback es menos preciso','El polling consume más CPU verificando constantemente','El callback solo funciona en autónomo'],correct:2},
],code:'',api_ref:''},

// ======================
// UNIDAD 3: MOTORES Y GRUPOS DE MOTORES (15 módulos)
// ======================
{id:21,unit:3,unitTitle:'Motores y Motor Groups',title:'Clase motor — Configuración y Tipos de Cartucho',level:'Intermedio',type:'lesson',free:false,duration:30,
desc:'Configura correctamente los Smart Motors V5 eligiendo el cartucho óptimo para tu aplicación.',
theory:`<h3>Cartuchos del V5 Smart Motor</h3><table style="width:100%;border-collapse:collapse"><tr style="border-bottom:1px solid #333"><th>Cartucho</th><th>RPM Libre</th><th>Torque</th><th>Uso</th></tr><tr style="border-bottom:1px solid #333"><td>Rojo (ratio36_1)</td><td>100 RPM</td><td>Alto</td><td>Brazos, elevadores</td></tr><tr style="border-bottom:1px solid #333"><td>Verde (ratio18_1)</td><td>200 RPM</td><td>Medio</td><td>Tracción general</td></tr><tr><td>Azul (ratio6_1)</td><td>600 RPM</td><td>Bajo</td><td>Flywheels, intakes</td></tr></table><p>El motor consume hasta <strong>11 Watts</strong> continuos con protección térmica a 55°C.</p>`,
code:`// Cartucho ROJO — 100 RPM (ratio36_1)\nmotor Brazo = motor(PORT2, ratio36_1, false);\n// Cartucho VERDE — 200 RPM (ratio18_1)\nmotor Traccion = motor(PORT1, ratio18_1, false);\n// Cartucho AZUL — 600 RPM (ratio6_1)\nmotor Flywheel = motor(PORT5, ratio6_1, false);\n// El tercer parámetro: false=normal, true=invertido\n// Invierte la dirección sin cambiar el cableado`,
api_ref:'vex::motor — constructor: port, gearSetting, reversed | ratio6_1, ratio18_1, ratio36_1', exercise:'Identifica qué cartucho necesita cada mecanismo de tu robot. Justifica tu elección con los datos técnicos. Documenta en el Engineering Notebook.'},

{id:22,unit:3,unitTitle:'Motores y Motor Groups',title:'motor.spin — Control de Velocidad y Dirección',level:'Intermedio',type:'lesson',free:false,duration:25,
desc:'Domina los métodos de control básico y avanzado de los motores V5.',
theory:`<h3>Métodos de Spin</h3><ul><li><code>spin(dir, vel, unit)</code> — Gira indefinidamente</li><li><code>spinFor(dir, rot, unit)</code> — Gira por rotaciones específicas</li><li><code>spinTo(pos, unit)</code> — Va a posición absoluta</li><li><code>spinToPosition(pos, unit, wait)</code> — Espera a llegar</li></ul><h3>Unidades de Velocidad</h3><p><code>pct</code> (0-100%), <code>rpm</code>, <code>volt</code> (control de voltaje directo — más lineal para PID).</p>`,
code:`motor Motor1 = motor(PORT1, ratio18_1, false);\n// Spin básico\nMotor1.spin(fwd, 70, pct);  // 70% adelante\nMotor1.spin(reverse, 50, pct); // 50% atrás\n// SpinFor — girar exactamente 2 rotaciones\nMotor1.spinFor(fwd, 2, rotations, true); // true = esperar\n// SpinTo — ir a posición absoluta 180°\nMotor1.spinToPosition(180, degrees, true);\n// Control por voltaje (más lineal para PID)\nMotor1.spin(fwd, 10.0, volt); // 10V de 12.8V max`,
api_ref:'vex::motor — spin(dir,vel,unit), spinFor(dir,rot,unit,wait), spinToPosition(pos,unit,wait)', exercise:'Programa el brazo de tu robot para moverse a 3 posiciones predefinidas (0°, 45°, 90°) usando spinToPosition. Mide el error en cada posición.'},

{id:23,unit:3,unitTitle:'Motores y Motor Groups',title:'Modos de Freno — coast, brake y hold',level:'Intermedio',type:'lesson',free:false,duration:20,
desc:'Elige el modo de freno correcto según tu mecanismo para evitar sobrecargar los motores.',
theory:`<h3>Los 3 Modos</h3><ul><li><code>coast</code> — Gira libremente al soltar. Suave, sin calor. Para drivetrain veloz.</li><li><code>brake</code> — Resistencia eléctrica al soltar. Freno activo sin calor constante. Para la mayoría de mecanismos.</li><li><code>hold</code> — Mantiene posición activamente usando corriente continua. Genera MUCHO calor. Solo para brazos que deben sostenerse.</li></ul><p><strong>Regla</strong>: Usa <code>hold</code> con precaución. Un motor en hold por más de 30 segundos puede superar los 55°C.</p>`,
code:`motor Brazo      = motor(PORT2, ratio36_1, false);\nmotor Traccion   = motor(PORT1, ratio18_1, false);\nmotor IntakeRollo= motor(PORT5, ratio6_1,  false);\n// Configurar modo de freno por defecto\nBrazo.setStopping(hold);       // Mencanismo elevador\nTraccion.setStopping(brake);   // Drivetrain\nIntakeRollo.setStopping(coast); // El intake puede rodar libre\n// También al parar individualmente:\nBrazo.stop(brakeType::hold);\nTraccion.stop(brakeType::brake);\nIntakeRollo.stop(brakeType::coast);`,
api_ref:'vex::motor — setStopping(brakeType) | stop(brakeType) | brakeType::coast, brake, hold', exercise:'Asigna el modo de freno correcto a cada motor de tu robot. Prueba con hold en el brazo por 60 segundos y mide la temperatura máxima.'},

{id:24,unit:3,unitTitle:'Motores y Motor Groups',title:'Encoders Integrados — Posición y Velocidad',level:'Intermedio',type:'lesson',free:false,duration:25,
desc:'El encoder del V5 Smart Motor ofrece 1800 ticks/revolución para control de precisión.',
theory:`<h3>El Encoder V5</h3><p>Cada V5 Smart Motor tiene un encoder integrado con resolución de <strong>1800 ticks por revolución</strong>. Es el sensor más preciso para control de posición sin hardware adicional.</p><h3>Funciones</h3><ul><li><code>position(degrees)</code> — Posición en grados desde el reset</li><li><code>position(rotations)</code> — En rotaciones completas</li><li><code>resetPosition()</code> — Reinicia a cero</li><li><code>velocity(rpm)</code> — Velocidad actual en RPM</li></ul>`,
code:`motor Motor1 = motor(PORT1, ratio18_1, false);\nvoid moverDistancia(double cm) {\n    const double CIRCUNFERENCIA_MM = M_PI * 101.6; // rueda 4"\n    const double MM_POR_GRADO = CIRCUNFERENCIA_MM / 360.0;\n    double grados_objetivo = (cm * 10.0) / MM_POR_GRADO;\n    Motor1.resetPosition();\n    Motor1.spin(fwd, 60, pct);\n    while(Motor1.position(degrees) < grados_objetivo) {\n        wait(10, msec);\n    }\n    Motor1.stop(brake);\n}`,
api_ref:'vex::motor — position(degrees), position(rotations), resetPosition(), velocity(rpm)', exercise:'Calibra cuántos grados del encoder corresponden a 1 cm de movimiento con tu rueda actual. Luego escribe una función moverCm(double cm) precisa ±0.5cm.'},

{id:25,unit:3,unitTitle:'Motores y Motor Groups',title:'Monitoreo Térmico y Eléctrico del Motor',level:'Intermedio',type:'lesson',free:false,duration:20,
desc:'Prevén sobrecalentamientos y protege tus motores durante competencia.',
theory:`<h3>Datos Eléctricos Clave</h3><ul><li><code>temperature(celsius)</code> — Temperatura interna (límite: 55°C)</li><li><code>current(amp)</code> — Corriente consumida (máx: ~2.5A continuo)</li><li><code>voltage(volt)</code> — Voltaje aplicado actualmente</li><li><code>power(watt)</code> — Potencia (P = V × I)</li><li><code>efficiency(pct)</code> — Eficiencia mecánica</li></ul><p>El motor <strong>reduce automáticamente</strong> su velocidad cuando supera 55°C.</p>`,
code:`motor Motor1 = motor(PORT1, ratio18_1, false);\nvoid monitorarMotor() {\n    double temp = Motor1.temperature(celsius);\n    double amp  = Motor1.current(amp);\n    double watt = Motor1.power(watt);\n    double eff  = Motor1.efficiency(pct);\n    Brain.Screen.printAt(10,40,"Temp: %.1f°C", temp);\n    Brain.Screen.printAt(10,70,"Corriente: %.2fA", amp);\n    Brain.Screen.printAt(10,100,"Potencia: %.1fW", watt);\n    Brain.Screen.printAt(10,130,"Eficiencia: %.0f%%", eff);\n    if (temp > 50) {\n        Brain.Screen.setPenColor(red);\n        Brain.Screen.printAt(10,160,"¡MOTOR CALIENTE!");\n    }\n}`,
api_ref:'vex::motor — temperature(celsius), current(amp), voltage(volt), power(watt), efficiency(pct)', exercise:'Corre el drivetrain a 100% por 30 segundos. Registra temperatura, corriente y eficiencia cada 5 segundos. Grafica los resultados e identifica el punto de saturación térmica.'},

{id:26,unit:3,unitTitle:'Motores y Motor Groups',title:'Clase motor_group — Control Sincronizado',level:'Intermedio',type:'lesson',free:false,duration:30,
desc:'Controla múltiples motores como uno solo con la clase motor_group.',
theory:`<h3>¿Cuándo usar motor_group?</h3><p>Un drivetrain de 4 motores (2 por lado) necesita que ambos motores del mismo lado se muevan exactamente igual. <code>motor_group</code> garantiza sincronización sin código duplicado.</p><h3>Ventajas</h3><ul><li>Un solo comando controla N motores</li><li>Velocidad y posición reflejan el promedio del grupo</li><li>Compatible con todos los métodos de <code>motor</code></li></ul>`,
code:`motor IzqF = motor(PORT1, ratio18_1, false);\nmotor IzqB = motor(PORT2, ratio18_1, false);\nmotor DerF = motor(PORT9, ratio18_1, true);\nmotor DerB = motor(PORT10, ratio18_1, true);\n// Crear grupos\nmotor_group Izq = motor_group(IzqF, IzqB);\nmotor_group Der = motor_group(DerF, DerB);\nvoid avanzar(double vel) {\n    Izq.spin(fwd, vel, pct);\n    Der.spin(fwd, vel, pct);\n}\nvoid detenerse() {\n    Izq.stop(brake);\n    Der.stop(brake);\n}\n// Posición del grupo (promedio de los motores)\ndouble pos = Izq.position(degrees);`,
api_ref:'vex::motor_group — constructor(m1,m2,...), spin(), stop(), position(), velocity()', exercise:'Reconfigura el drivetrain de tu robot usando motor_group. Verifica que ambos motores de cada lado giran exactamente al mismo tiempo con la misma velocidad.'},

{id:27,unit:3,unitTitle:'Motores y Motor Groups',title:'Relaciones de Engranajes — Cálculo Técnico',level:'Avanzado',type:'lesson',free:false,duration:40,
desc:'Calcula velocidad lineal, torque y RPM real de tu drivetrain con cualquier configuración.',
theory:`<h3>Fórmula Base</h3><p style="font-size:1.2rem;padding:0.8rem;background:#1a1a1a;border-radius:8px;text-align:center"><strong>RPM_salida = RPM_entrada × (Dientes_driver / Dientes_driven)</strong></p><h3>Velocidad Lineal</h3><p>Vel (m/s) = RPM_rueda × π × Diámetro(m) / 60</p><h3>Ruedas VEX más comunes</h3><ul><li>2" Omni = 50.8mm de diámetro</li><li>3.25" Traction = 82.55mm</li><li>4" Omni = 101.6mm</li></ul>`,
code:`#include <cmath>\n// Función: calcular velocidad lineal real del robot\ndouble calcularVelocidad(\n    double rpm_motor,    // RPM libres del cartucho\n    int dientes_driver,  // engrane en el eje del motor  \n    int dientes_driven,  // engrane en la rueda\n    double diametro_mm   // diámetro de la rueda\n) {\n    double rpm_rueda = rpm_motor * ((double)dientes_driver / dientes_driven);\n    double vel_m_s   = (rpm_rueda * M_PI * (diametro_mm/1000.0)) / 60.0;\n    return vel_m_s;\n}\n// Ejemplo: Motor verde(200RPM), engranes 36:60, rueda 4"(101.6mm)\n// vel = calcularVelocidad(200, 36, 60, 101.6) = ~0.64 m/s`,
api_ref:'Mecánica de engranajes — relación de transmisión', exercise:'Calcula la velocidad teórica de tu drivetrain. Luego mídela con el encoder (distancia/tiempo). Calcula el % de eficiencia real vs. teórico. Target competitivo: >75% eficiencia.'},

{id:28,unit:3,unitTitle:'Motores y Motor Groups',title:'setMaxTorque y setStopping — Control de Límites',level:'Avanzado',type:'lesson',free:false,duration:20,
desc:'Protege tus mecanismos mecánicamente con límites de torque por software.',
theory:`<h3>Control de Torque</h3><p><code>setMaxTorque(val, unit)</code> limita el torque máximo que puede aplicar el motor. Ideal para:</p><ul><li>Proteger mecanismos delicados de auto-romperse</li><li>Intakes que atrapan objetos (limitar compresión)</li><li>Brazos con posición de home contra un tope físico</li></ul><p>Unidades: <code>pct</code>, <code>Nm</code> (Newton-metro), <code>InLb</code></p>`,
code:`motor Intake = motor(PORT5, ratio6_1, false);\nmotor Brazo  = motor(PORT2, ratio36_1, false);\n// Limitar el intake al 70% del torque máximo\n// Permite atrapar piezas sin romper la mecánica\nIntake.setMaxTorque(70, pct);\n// El brazo puede ir a home contra un tope físico\n// sin dañar engranes (limitando a 30%)\nBrazo.setMaxTorque(30, pct);\nBrazo.spinFor(reverse, 5, rotations); // va a home\nBrazo.setMaxTorque(100, pct); // restaurar para uso normal`,
api_ref:'vex::motor — setMaxTorque(val, unit) | torqueUnits::pct, Nm, InLb', exercise:'Prueba tu mecanismo de agarre con diferentes límites de torque (30%, 50%, 70%). Encuentra el punto donde agarra la pieza firmemente sin dañarla.'},

{id:29,unit:3,unitTitle:'Motores y Motor Groups',title:'PID de Posición en Motores V5',level:'Avanzado',type:'lesson',free:false,duration:50,
desc:'El motor V5 tiene PID interno. Aprende a usarlo y cuándo implementar el tuyo propio.',
theory:`<h3>PID Interno del V5</h3><p>Cuando usas <code>spinToPosition()</code> o <code>spinFor()</code>, el motor ejecuta su propio controlador PID interno. Para la mayoría de casos es suficientemente bueno.</p><h3>¿Cuándo implementar PID propio?</h3><ul><li>Giros con el IMU (el encoder no mide ángulos de chassis)</li><li>Movimiento recto (corrección de deriva)</li><li>Odometría (posición 2D del robot)</li><li>Necesitas latencia ultra-baja (< 10ms)</li></ul>`,
code:`// PID personalizado para giro del robot\ninertial Imu = inertial(PORT7);\nmotor_group Izq = motor_group(IzqF, IzqB);\nmotor_group Der = motor_group(DerF, DerB);\ndouble Kp=0.8, Ki=0.001, Kd=4.0;\nvoid girarA(double target, double vel_max) {\n    double error, prev_error=0, integral=0;\n    do {\n        error = target - Imu.heading(degrees);\n        if(error>180) error-=360; if(error<-180) error+=360;\n        integral += error;\n        double deriv = error - prev_error;\n        double vel = Kp*error + Ki*integral + Kd*deriv;\n        vel = fmax(-vel_max, fmin(vel_max, vel));\n        Izq.spin(fwd,  vel, pct);\n        Der.spin(fwd, -vel, pct);\n        prev_error = error;\n        wait(10, msec);\n    } while(fabs(error) > 1.5);\n    Izq.stop(brake); Der.stop(brake);\n}`,
api_ref:'vex::inertial — heading(degrees) | vex::motor_group — spin()', exercise:'Implementa el PID de giro y ajusta Kp, Ki, Kd para lograr giros de 90° con error menor a 2°. Prueba 10 giros consecutivos y registra el error promedio.'},

{id:30,unit:3,unitTitle:'Motores y Motor Groups',title:'Control de Mecánismos Complejos — Lifts e Intakes',level:'Avanzado',type:'lesson',free:false,duration:45,
desc:'Programa elevadores, intakes y catapultas con control preciso y gestión de estados.',
theory:`<h3>Máquina de Estados</h3><p>Un mecanismo complejo tiene estados definidos. Usa un enum para manejarlos limpiamente:</p><ul><li>Lift: ABAJO, SUBIENDO, ARRIBA, BAJANDO</li><li>Intake: APAGADO, INGIRIENDO, ESCUPIENDO</li><li>Catapulta: CARGANDO, CARGADA, DISPARANDO</li></ul>`,
code:`enum EstadoLift { ABAJO, SUBIENDO, ARRIBA, BAJANDO };\nEstadoLift estadoActual = ABAJO;\nmotor Lift1 = motor(PORT3, ratio36_1, false);\nmotor Lift2 = motor(PORT4, ratio36_1, true);\nmotor_group Lift = motor_group(Lift1, Lift2);\nvoid actualizarLift() {\n    switch(estadoActual) {\n        case ABAJO:\n            Lift.stop(hold);\n            if(Control.ButtonL1.pressing()) {\n                estadoActual = SUBIENDO;\n            }\n            break;\n        case SUBIENDO:\n            Lift.spin(fwd, 80, pct);\n            if(Lift.position(degrees) > 720) {\n                estadoActual = ARRIBA;\n            }\n            break;\n        case ARRIBA:\n            Lift.stop(hold);\n            if(Control.ButtonL2.pressing()) {\n                estadoActual = BAJANDO;\n            }\n            break;\n        case BAJANDO:\n            Lift.spin(reverse, 60, pct);\n            if(Lift.position(degrees) < 50) {\n                estadoActual = ABAJO;\n                Lift.resetPosition();\n            }\n            break;\n    }\n}`,
api_ref:'enum, switch/case | vex::motor_group — spin, stop(hold), position(degrees)', exercise:'Implementa una máquina de estados para el mecanismo más complejo de tu robot. El sistema debe ser robusto: si el piloto presiona el botón en estado incorrecto, no debe crashear.'},

{id:31,unit:3,unitTitle:'Motores y Motor Groups',title:'Examen Unidad 3 — Motores',level:'Intermedio',type:'exam',free:false,duration:15,
desc:'Examen de motores, cartuchos y contro mecánico.',exam:[
{q:'¿Cuántos ticks por revolución tiene el encoder del V5 Smart Motor?',options:['360','720','1800','3600'],correct:2},
{q:'Para un elevador pesado que debe mantener posición, el mejor modo de freno es:',options:['coast','brake','hold','ningunoa'],correct:2},
{q:'Un motor Verde con engranes 12:84 tiene RPM de salida:',options:['100 RPM','200 RPM','28.57 RPM','1400 RPM'],correct:2},
{q:'¿Cuál clase controla múltiples motores sincrónicamente?',options:['motor_pair','motor_sync','motor_group','multi_motor'],correct:2},
{q:'La temperatura límite del V5 Smart Motor antes de reducir potencia es:',options:['45°C','55°C','65°C','75°C'],correct:1},
],code:'',api_ref:''},
];
