// VEX Academy Curriculum — Part 2: Units 4-6 (Módulos 32-75)
const CURRICULUM_P2 = [
// ======================
// UNIDAD 4: TREN MOTRIZ (DRIVETRAIN) Y SMARTDRIVE (10 módulos)
// ======================
{id:32,unit:4,unitTitle:'Drivetrain y SmartDrive',title:'Clase drivetrain — Configuración Base',level:'Intermedio',type:'lesson',free:false,duration:30,
desc:'La clase drivetrain simplifica el control de chasis para equipos que inician.',
theory:`<h3>Drivetrain Simplificado</h3><p>La clase <code>drivetrain</code> abstrae el control de tracción con funciones de alto nivel. Ideal para aprender. Para competencia avanzada, controla los motores directamente con PID.</p><h3>Parámetros Críticos</h3><ul><li><strong>wheelTravel</strong>: Circunferencia de la rueda (mm)</li><li><strong>trackWidth</strong>: Distancia entre ruedas izquierda y derecha (mm)</li><li><strong>wheelBase</strong>: Distancia entre eje delantero y trasero (mm)</li></ul>`,
code:`motor IzqF = motor(PORT1,  ratio18_1, false);\nmotor DerF = motor(PORT10, ratio18_1, true);\nmotor_group Izq = motor_group(IzqF);\nmotor_group Der = motor_group(DerF);\n// wheelTravel=319mm (rueda 4"), trackWidth=304mm, wheelBase=152mm\ndrivetrain DT = drivetrain(Izq, Der, 319, 304, 152, mm, 1);\n// Movimientos de alto nivel\nDT.drive(fwd);              // avanzar indefinido\nDT.driveFor(fwd, 30, cm);   // avanzar 30cm\nDT.turn(right);             // girar\nDT.turnFor(right, 90, degrees, true); // girar 90°\nDT.stop(brake);`,
api_ref:'vex::drivetrain — drive(dir), driveFor(dir,dist,unit), turn(dir), turnFor(dir,deg,unit)', exercise:'Configura la clase drivetrain con las medidas exactas de tu robot. Calibra driveFor() para que 30cm reales sean 30cm programados (tolerancia ±1cm).'},

{id:33,unit:4,unitTitle:'Drivetrain y SmartDrive',title:'Clase smartdrive — Integración con IMU',level:'Avanzado',type:'lesson',free:false,duration:40,
desc:'smartdrive combina drivetrain + IMU para giros y posicionamiento de alta precisión.',
theory:`<h3>SmartDrive = Drivetrain + IMU</h3><p>La clase <code>smartdrive</code> hereda de <code>drivetrain</code> pero usa el Inertial Sensor para giros. Esto da giros±2° de precisión vs. ±10-20° sin IMU.</p><h3>Funciones Nuevas</h3><ul><li><code>turnToHeading(deg)</code> — Girar a ángulo absoluto del campo</li><li><code>turnToRotation(deg)</code> — Girar relativo al inicio</li><li><code>setDriveVelocity(vel, pct)</code> — Velocidad base</li><li><code>setTurnVelocity(vel, pct)</code> — Velocidad de giro</li></ul>`,
code:`inertial Imu = inertial(PORT7);\nmotor_group Izq = motor_group(IzqF, IzqB);\nmotor_group Der = motor_group(DerF, DerB);\nsmartdrive Robot = smartdrive(Izq, Der, Imu, 319, 304, 152, mm, 1);\nvoid pre_auton() {\n    Imu.calibrate();\n    while(Imu.isCalibrating()) { wait(100,msec); }\n    Robot.setDriveVelocity(60, pct);\n    Robot.setTurnVelocity(50, pct);\n}\nvoid autonomous() {\n    Robot.driveFor(fwd, 60, cm, true);\n    Robot.turnToHeading(90, degrees, true);  // Norte del campo\n    Robot.driveFor(fwd, 30, cm, true);\n    Robot.turnToHeading(0, degrees, true);   // Regresa al norte\n}`,
api_ref:'vex::smartdrive — turnToHeading(deg,unit,wait), turnToRotation(), setDriveVelocity()', exercise:'Programa un autónomo que use turnToHeading() para navegación absoluta de campo. El robot debe llegar a 3 waypoints definidos en ángulos absolutos.'},

{id:34,unit:4,unitTitle:'Drivetrain y SmartDrive',title:'Configuración de Chasis y Tipos de Ruedas',level:'Intermedio',type:'lesson',free:false,duration:25,
desc:'Elige el tipo de chasis y ruedas correctas para maximizar el rendimiento en competencia.',
theory:`<h3>Tipos de Ruedas VEX</h3><ul><li><strong>Omni Wheels</strong>: Se mueven en cualquier dirección. Rollers perpendiculares. Ideales para giros.</li><li><strong>Traction Wheels</strong>: Mayor agarre, menos deslizamiento lateral. Para pushing.</li><li><strong>Mecanum</strong>: Movimiento holonómico (strafe). Complejo pero versátil.</li></ul><h3>Configuraciones Comunes</h3><ul><li><strong>Tank (skid-steer)</strong>: 2 o 4 ruedas, más simple, más torque.</li><li><strong>X-Drive/holonómico</strong>: 4 ruedas a 45°, movimiento en todas direcciones.</li></ul>`,
code:`// Calcular wheelTravel según tu rueda:\n// Rueda 4" Omni: C = π × 101.6mm = 319.15mm\n// Rueda 3.25" Traction: C = π × 82.55mm = 259.3mm\n// Medir trackWidth con cinta métrica (centro-centro ruedas)\n// Medir wheelBase = distancia entre ejes\n// Para X-Drive (ruedas a 45°), la fórmula del wheelTravel es diferente:\n// wheelTravel = π × diámetro × cos(45°) = C × 0.707`,
api_ref:'Mecánica de chasis — tipos de ruedas y configuraciones', exercise:'Mide con precisión las 3 dimensiones de tu chasis (wheelTravel, trackWidth, wheelBase) y documenta con foto en el Engineering Notebook. Calibra el error de posición.'},

{id:35,unit:4,unitTitle:'Drivetrain y SmartDrive',title:'Control de Drivetrain — Arcade Drive vs Tank Drive',level:'Intermedio',type:'lesson',free:false,duration:25,
desc:'Implementa los esquemas de control más usados en competencia VEX.',
theory:`<h3>Arcade Drive</h3><p>Un joystick controla velocidad (eje Y) y el otro giro (eje X). Es el estándar de competencia — los pilotos tienen más control fino.</p><h3>Tank Drive</h3><p>Joystick izquierdo = motor izquierdo, derecho = motor derecho. Más intuitivo para principiantes pero más difícil de ir recto.</p><h3>Curva de Respuesta</h3><p>Aplica una curva exponencial a los joysticks para mayor precisión a bajas velocidades sin perder potencia máxima.</p>`,
code:`controller Control = controller(primary);\nmotor_group Izq = motor_group(IzqF, IzqB);\nmotor_group Der = motor_group(DerF, DerB);\n// Curva exponencial (más suave en centro)\ndouble curva(int raw, double exp) {\n    return (pow(fabs(raw), exp) / pow(100, exp-1)) * (raw<0?-1:1);\n}\nvoid usercontrol() {\n    while(true) {\n        // ARCADE DRIVE con curva\n        double fwd  = curva(Control.Axis3.position(), 1.5);\n        double turn = curva(Control.Axis1.position(), 1.5);\n        Izq.spin(fwd, fwd+turn, pct);\n        Der.spin(fwd, fwd-turn, pct);\n        wait(20, msec);\n    }\n}`,
api_ref:'vex::controller — Axis1.position(), Axis3.position() | vex::motor_group — spin()', exercise:'Implementa Arcade Drive con curva exponencial de potencia 1.5. Compara con control lineal. ¿Cuál da más precisión en maniobras lentas? Documenta con cronómetro.'},

{id:36,unit:4,unitTitle:'Drivetrain y SmartDrive',title:'Corrección de Trayectoria con IMU (Drive Recto)',level:'Avanzado',type:'lesson',free:false,duration:45,
desc:'Mantén líneas perfectamente rectas en el autónomo corrigiendo la deriva con el IMU.',
theory:`<h3>El Problema de la Deriva</h3><p>Ningún drivetrain va perfectamente recto. Pequeñas diferencias en los motores, fricción y piso hacen que el robot se curve. En 2 metros puede desviarse 10-20cm sin corrección.</p><h3>Solución: PID de Heading</h3><p>Mientras el robot avanza, monitorea el heading del IMU y aplica una corrección proporcional a los motores para mantener el ángulo constante.</p>`,
code:`inertial Imu = inertial(PORT7);\nmotor_group Izq = motor_group(IzqF, IzqB);\nmotor_group Der = motor_group(DerF, DerB);\nvoid avanzarRecto(double dist_cm, double vel_pct) {\n    const double MM_POR_GRADO = (M_PI * 101.6) / 360.0;\n    double target = (dist_cm * 10.0) / MM_POR_GRADO;\n    double headingRef = Imu.heading(degrees);\n    Izq.resetPosition();\n    const double Kp_heading = 0.5;\n    while(Izq.position(degrees) < target) {\n        double error_h = Imu.heading(degrees) - headingRef;\n        if(error_h > 180) error_h -= 360;\n        if(error_h < -180) error_h += 360;\n        double correc = Kp_heading * error_h;\n        Izq.spin(fwd, vel_pct - correc, pct);\n        Der.spin(fwd, vel_pct + correc, pct);\n        wait(10, msec);\n    }\n    Izq.stop(brake); Der.stop(brake);\n}`,
api_ref:'vex::inertial — heading(degrees) | vex::motor_group — spin(), position()', exercise:'Prueba tu función avanzarRecto() a 100cm, 150cm y 200cm. Mide el error lateral en cada caso. Con corrección debe ser < 2cm. Sin corrección documenta la diferencia.'},

// ======================
// UNIDAD 5: EL CONTROLADOR (10 módulos)
// ======================
{id:37,unit:5,unitTitle:'El Controlador',title:'Clase controller — Configuración y Canales',level:'Básico',type:'lesson',free:false,duration:20,
desc:'El controlador V5 es el puente entre el piloto y el robot. Domina cada función.',
theory:`<h3>Controladores en VEX</h3><p>VEX permite 2 controladores: <code>primary</code> (piloto principal) y <code>partner</code> (co-piloto). Cada uno tiene:</p><ul><li><strong>4 joysticks</strong> (Axis1-Axis4), rango -100 a 100</li><li><strong>12 botones</strong>: A,B,X,Y, L1,L2,R1,R2, Up,Down,Left,Right</li><li><strong>Pantalla LCD</strong> de 3 líneas</li><li><strong>Motor de vibración</strong> (rumble)</li></ul>`,
code:`controller Control  = controller(primary);\ncontroller Copiloto = controller(partner);\nint main() {\n    // Leer joysticks (-100 a 100)\n    int fwd  = Control.Axis3.position(); // eje Y izq\n    int turn = Control.Axis1.position(); // eje X der\n    int brazo= Copiloto.Axis3.position(); // co-piloto\n    // Leer botones\n    bool aPresionado = Control.ButtonA.pressing();\n    bool l1Presionado= Control.ButtonL1.pressing();\n    // Pantalla del control\n    Control.Screen.print("Temp: %.0f", Motor1.temperature(celsius));\n    // Vibración de alerta\n    Control.rumble("...");\n}`,
api_ref:'vex::controller — Axis1-4.position(), ButtonA-Y.pressing(), Screen.print(), rumble()', exercise:'Configura el control para piloto + copiloto. El piloto maneja tracción y el copiloto maneja mecanismos. Implementa el sistema completo en usercontrol().'},

{id:38,unit:5,unitTitle:'El Controlador',title:'Botones — pressed(), released() y Eventos',level:'Intermedio',type:'lesson',free:false,duration:25,
desc:'Implementa controles responsivos y eficientes con callbacks de botones.',
theory:`<h3>Diferencia entre pressing() y pressed()</h3><ul><li><code>pressing()</code> — true MIENTRAS el botón está pulsado (polling)</li><li><code>pressed(callback)</code> — ejecuta función al MOMENTO de presionar (evento)</li><li><code>released(callback)</code> — ejecuta función al soltar</li></ul><p>Para mecanismos tipo toggle (encender/apagar con un botón) usa el evento <code>pressed</code> para mayor responsividad.</p>`,
code:`controller Control = controller(primary);\nmotor Intake = motor(PORT5, ratio6_1, false);\nbool intakeActivo = false;\n// Toggle limpio con callback\nvoid toggleIntake() {\n    intakeActivo = !intakeActivo;\n    if(intakeActivo) {\n        Intake.spin(fwd, 100, pct);\n        Control.Screen.clearLine(1);\n        Control.Screen.print("INTAKE: ON");\n    } else {\n        Intake.stop(coast);\n        Control.Screen.clearLine(1);\n        Control.Screen.print("INTAKE: OFF");\n    }\n}\nvoid setupCallbacks() {\n    Control.ButtonA.pressed(toggleIntake);\n    Control.ButtonB.released([](){\n        // Inline lambda — para acciones simples\n        Brazo.stop(hold);\n    });\n}`,
api_ref:'vex::controller — ButtonA.pressed(fn), ButtonA.released(fn), ButtonA.pressing()', exercise:'Convierte todos los controles que usas en tu usercontrol() de pressing() a callbacks. Mide si hay diferencia en la respuesta del robot.'},

{id:39,unit:5,unitTitle:'El Controlador',title:'Pantalla del Controlador — HUD del Piloto',level:'Intermedio',type:'lesson',free:false,duration:20,
desc:'Muestra datos críticos al piloto en tiempo real para toma de decisiones en competencia.',
theory:`<h3>La Pantalla LCD del Control</h3><p>El controlador tiene una pantalla de 3 líneas de texto. Es el <strong>HUD del piloto</strong> durante el juego. Muestra información que no puede verse en el Brain.</p><h3>Qué mostrar</h3><ul><li>Línea 1: Batería % y temperatura del motor más caliente</li><li>Línea 2: Estado del mecanismo principal</li><li>Línea 3: Tiempo restante o puntuación estimada</li></ul>`,
code:`controller Control = controller(primary);\nvoid actualizarHUD() {\n    // Actualizar cada 500ms para no saturar\n    static uint32_t ultimaActualizacion = 0;\n    if(Brain.Timer.time(msec) - ultimaActualizacion < 500) return;\n    ultimaActualizacion = Brain.Timer.time(msec);\n    // Línea 1: Batería\n    Control.Screen.setCursor(1, 1);\n    Control.Screen.print("Bat:%.0f%% T:%.0f",\n        Brain.Battery.capacity(pct),\n        MotorIzqF.temperature(celsius));\n    // Línea 2: Estado\n    Control.Screen.setCursor(2, 1);\n    Control.Screen.print("Intake:%s", intakeActivo?"ON":"OFF");\n    // Línea 3: Contador de piezas\n    Control.Screen.setCursor(3, 1);\n    Control.Screen.print("Piezas: %d", contadorPiezas);\n}`,
api_ref:'vex::controller — Screen.setCursor(row,col), Screen.print(fmt,...), Screen.clearLine(n)', exercise:'Diseña el HUD completo de tu piloto con las 3 líneas. Incluye batería, estado de mecanismo y cualquier dato crítico. Prueba durante una sesión de práctica.'},

{id:40,unit:5,unitTitle:'El Controlador',title:'Rumble y Haptic Feedback',level:'Básico',type:'lesson',free:false,duration:15,
desc:'Usa la vibración del controlador como alertas táctiles durante juego.',
theory:`<h3>Control.rumble(pattern)</h3><p>El patrón usa <code>.</code> para pulso corto y <code>-</code> para pulso largo. Máximo 6 caracteres.</p><h3>Casos de Uso</h3><ul><li><code>"."</code> — Pieza captada (confirmación)</li><li><code>"-"</code> — Alerta de temperatura alta</li><li><code>"..."</code> — 5 segundos restantes (3 pulsos)</li><li><code>"-.-"</code> — Error de sistema</li></ul><p>Extra: El controlador también vibra cuando hay pérdida de señal.</p>`,
code:`controller Control = controller(primary);\nvoid onPiezaCaptada() {\n    Control.rumble("."); // pulso corto de confirmación\n    contadorPiezas++;\n}\nvoid alertaTemperatura() {\n    if(Motor1.temperature(celsius) > 50) {\n        Control.rumble("-"); // vibración larga de alerta\n    }\n}\nvoid cincoSegundosRestantes() {\n    // Llamar cuando quedan 5 segundos de driver\n    Control.rumble("...");\n    Control.Screen.setCursor(3,1);\n    Control.Screen.print("!!! 5 SEG !!!");\n}`,
api_ref:'vex::controller — rumble(pattern) | pattern: . corto, - largo', exercise:'Implementa 3 alertas de rumble para tu robot: captura de pieza, motor caliente y 5 segundos restantes del período. Prueba que el piloto las distingue sin mirar.'},

{id:41,unit:5,unitTitle:'El Controlador',title:'Control Múltiple — Copiloto Strategies',level:'Avanzado',type:'lesson',free:false,duration:30,
desc:'Maximiza el rendimiento con roles definidos entre piloto y copiloto.',
theory:`<h3>División de Roles</h3><p>Los mejores equipos VEX separan responsabilidades claramente:</p><ul><li><strong>Piloto</strong>: Solo tracción + 1-2 botones básicos</li><li><strong>Copiloto</strong>: Todos los mecanismos (intake, elevador, etc.)</li></ul><h3>Ventajas</h3><p>Permite maniobras complejas simultáneas. El piloto puede enfocarse en posicionamiento mientras el copiloto opera mecanismos independientemente.</p>`,
code:`controller Piloto  = controller(primary);\ncontroller Copil   = controller(partner);\nvoid usercontrol() {\n    while(true) {\n        // PILOTO: Solo tracción\n        int fwd  = Piloto.Axis3.position();\n        int turn = Piloto.Axis1.position();\n        Izq.spin(fwd, fwd+turn, pct);\n        Der.spin(fwd, fwd-turn, pct);\n        // COPILOTO: Mecanismos\n        // Intake\n        if(Copil.ButtonR1.pressing()) Intake.spin(fwd, 100, pct);\n        else if(Copil.ButtonR2.pressing()) Intake.spin(reverse, 100, pct);\n        else Intake.stop(coast);\n        // Elevador (control analógico del copiloto)\n        int velLift = Copil.Axis3.position();\n        if(fabs(velLift) > 5) Lift.spin(fwd, velLift, pct);\n        else Lift.stop(hold);\n        wait(20, msec);\n    }\n}`,
api_ref:'vex::controller — primary, partner - dos controladores simultáneos', exercise:'Define los roles de piloto y copiloto para tu robot. Practica 10 partidas con la división. ¿Cuánto mejora el puntaje vs. control de un solo jugador?'},

{id:42,unit:5,unitTitle:'El Controlador',title:'Examen Unidad 5 — El Controlador',level:'Básico',type:'exam',free:false,duration:10,
desc:'Verifica tu dominio del controlador VEX V5 y sus modos de control.',exam:[
{q:'¿Cuántos joysticks tiene el controlador V5?',options:['2','3','4','6'],correct:2},
{q:'¿Cuál es la diferencia entre pressing() y pressed()?',options:['No hay','pressing es un evento','pressed() retorna true mientras está pulsado, pressing() al momento de presionar','pressing() es estado continuo, pressed() es evento de disparo único'],correct:3},
{q:'¿Cuántas líneas tiene la pantalla del controlador V5?',options:['1','2','3','4'],correct:2},
{q:'El patrón de rumble "..." significa:',options:['Un pulso largo','3 pulsos cortos','Error del sistema','Señal de radio perdida'],correct:1},
{q:'Para controlar mecanismos con toggle, el mejor método es:',options:['pressing() en loop','pressed() con callback','released() siempre','ButtonA.value()'],correct:1},
],code:'',api_ref:''},

// ======================
// UNIDAD 6: SENSORES SMART PORT (15 módulos)
// ======================
{id:43,unit:6,unitTitle:'Sensores VEX V5 Smart Port',title:'Sensor Inercial (IMU) — Specs y Calibración',level:'Básico',type:'lesson',free:true,duration:35,
desc:'El sensor más crítico en competencia. Domina el giroscopio de 6 ejes del IMU V5.',
theory:`<h3>Especificaciones Técnicas</h3><table style="width:100%;border-collapse:collapse;font-size:0.9rem"><tr style="border-bottom:1px solid #333"><td><strong>Acelerómetro</strong></td><td>3 ejes, ±4g máximo</td></tr><tr style="border-bottom:1px solid #333"><td><strong>Giroscopio</strong></td><td>3 ejes, ±1000°/segundo</td></tr><tr style="border-bottom:1px solid #333"><td><strong>Calibración</strong></td><td>~2 segundos (robot inmóvil)</td></tr><tr><td><strong>Uso</strong></td><td>Heading, yaw, pitch, roll, aceleración</td></tr></table><p><strong>Regla de Oro</strong>: Siempre calibra en <code>pre_auton()</code> con el robot COMPLETAMENTE inmóvil.</p>`,
code:`inertial Imu = inertial(PORT7);\nvoid pre_auton() {\n    Brain.Screen.printAt(10,40,"Calibrando IMU...");\n    Imu.calibrate();\n    // Esperar hasta que termine (obligatorio)\n    while(Imu.isCalibrating()) { wait(100, msec); }\n    Brain.Screen.printAt(10,40,"IMU Listo! ");\n    // Verificar\n    double heading = Imu.heading(degrees); // debe ser ~0\n    Brain.Screen.printAt(10,70,"Heading: %.2f°", heading);\n}`,
api_ref:'vex::inertial — calibrate(), isCalibrating(), heading(degrees), rotation(degrees), pitch(), roll(), yaw(), acceleration()', exercise:'Calibra el IMU y mide el heading después de: 1) girar 90°, 2) regresar a 0°. Repite 5 veces. Calcula el drift acumulado máximo observado.'},

{id:44,unit:6,unitTitle:'Sensores VEX V5 Smart Port',title:'IMU — heading(), rotation() y Ejes de Rotación',level:'Intermedio',type:'lesson',free:true,duration:30,
desc:'Entiende la diferencia entre heading y rotation y cómo cada eje afecta tu control.',
theory:`<h3>heading() vs rotation()</h3><ul><li><code>heading(degrees)</code> — Ángulo ABSOLUTO del campo: siempre 0-359°. Como una brújula.</li><li><code>rotation(degrees)</code> — Rotación ACUMULADA. Puede ser -1000° o +720° (sin límite). Mejor para contar vueltas.</li></ul><h3>Los 3 Ejes</h3><ul><li><strong>Yaw</strong> (girar en plano horizontal) — el más usado en drivetrain</li><li><strong>Pitch</strong> (inclinación adelante/atrás)</li><li><strong>Roll</strong> (inclinación lateral)</li></ul>`,
code:`inertial Imu = inertial(PORT7);\nvoid displayIMU() {\n    double heading  = Imu.heading(degrees);   // 0-359°\n    double rotation = Imu.rotation(degrees);  // acumulado\n    double pitch    = Imu.pitch(degrees);     // inclinación F/B\n    double roll     = Imu.roll(degrees);      // inclinación L/R\n    double yaw      = Imu.yaw(degrees);       // mismo que rotation\n    // Aceleración (detección de colisiones)\n    double ax = Imu.acceleration(xaxis); // en g\n    double ay = Imu.acceleration(yaxis);\n    double az = Imu.acceleration(zaxis);\n    // Detección de colisión\n    if(fabs(ax) > 2.0 || fabs(ay) > 2.0) {\n        Brain.Screen.printAt(10,80,"¡IMPACTO DETECTADO!");\n    }\n}`,
api_ref:'vex::inertial — heading(), rotation(), pitch(), roll(), yaw(), acceleration(axis)', exercise:'Usa pitch() y roll() para detectar cuando el robot sube una rampa. Programa que el robot reduzca velocidad al 50% cuando pitch > 15°.'},

{id:45,unit:6,unitTitle:'Sensores VEX V5 Smart Port',title:'Sensor de Distancia — Láser Clase 1',level:'Básico',type:'lesson',free:true,duration:35,
desc:'Detección precisa de objetos para pickup automático y alineación de arena.',
theory:`<h3>Especificaciones Técnicas</h3><table style="width:100%;border-collapse:collapse;font-size:0.9rem"><tr style="border-bottom:1px solid #333"><td><strong>Tipo</strong></td><td>Láser Clase 1 (seguro)</td></tr><tr style="border-bottom:1px solid #333"><td><strong>Rango</strong></td><td>20 mm — 2,000 mm</td></tr><tr style="border-bottom:1px solid #333"><td><strong>Precisión</strong></td><td>±15mm &lt;200mm | ±5% &gt;200mm</td></tr><tr><td><strong>Velocidad</strong></td><td>objectVelocity() en m/s</td></tr></table>`,
code:`distance SensorDist = distance(PORT3);\nvoid detectarObjeto() {\n    if(SensorDist.isObjectDetected()) {\n        double dist_mm = SensorDist.objectDistance(mm);\n        double vel_ms  = SensorDist.objectVelocity();\n        int    size    = SensorDist.objectSize(); // 0=pequeño,1=mediano,2=grande\n        // Activar intake automático si objeto cerca\n        if(dist_mm < 150 && dist_mm > 20) {\n            Intake.spin(fwd, 100, pct);\n        } else {\n            Intake.stop(coast);\n        }\n        // Detectar objeto acercándose (vel negativa)\n        if(vel_ms < -0.1) {\n            Brain.Screen.printAt(10,80,"Objeto acercándose!");\n        }\n    }\n}`,
api_ref:'vex::distance — objectDistance(mm), objectVelocity(), objectSize(), isObjectDetected()', exercise:'Implementa un intake auto-activado con el Distance Sensor. Debe turn on si hay un objeto a <15cm y off cuando no hay objeto. Mide la latencia de respuesta.'},

{id:46,unit:6,unitTitle:'Sensores VEX V5 Smart Port',title:'Sensor de Visión — Configuración y Firmas',level:'Avanzado',type:'lesson',free:false,duration:45,
desc:'Detecta y sigue objetos por color con la cámara de 640×400px para scoring automático.',
theory:`<h3>Especificaciones Técnicas</h3><table style="width:100%;border-collapse:collapse;font-size:0.9rem"><tr style="border-bottom:1px solid #333"><td><strong>Resolución</strong></td><td>640 × 400 px</td></tr><tr style="border-bottom:1px solid #333"><td><strong>Frecuencia</strong></td><td>50 Hz</td></tr><tr style="border-bottom:1px solid #333"><td><strong>Firmas</strong></td><td>7 colores simultáneas</td></tr></table><p>Configura las firmas con la VEX Vision Utility (incluida en VS Code). Capta una muestra del objeto bajo la iluminación del torneo.</p>`,
code:`vision SensorVision = vision(PORT8);\n// Firma configurada con VEX Vision Utility\nvision::signature ROJO = vision::signature(\n    1, 7723, 9867, 8795, -1163, -623, -893, 2.5, 0);\nvoid seguirObjeto() {\n    SensorVision.takeSnapshot(ROJO);\n    if(SensorVision.objectCount > 0) {\n        vision::object obj = SensorVision.largestObject;\n        int cx = obj.centerX;  // 0-639\n        int cy = obj.centerY;  // 0-399\n        int w  = obj.width;\n        int h  = obj.height;\n        // Control proporcional para centrar\n        int error = cx - 320; // 320 = centro\n        double vel_giro = 0.1 * error;\n        Izq.spin(fwd, 50 + vel_giro, pct);\n        Der.spin(fwd, 50 - vel_giro, pct);\n    } else {\n        Izq.stop(); Der.stop();\n    }\n}`,
api_ref:'vex::vision — takeSnapshot(sig), objectCount, largestObject, object.centerX/Y/width/height', exercise:'Configura una firma para el color de objetivo de este año. Programa el robot para girarse automáticamente hacia el objeto y avanzar hasta estar a 30cm de él.'},

{id:47,unit:6,unitTitle:'Sensores VEX V5 Smart Port',title:'Sensor Óptico — Color, Hue y Proximidad',level:'Intermedio',type:'lesson',free:false,duration:30,
desc:'Detecta colores exactos y cuenta piezas en el intake automáticamente.',
theory:`<h3>Optical Sensor</h3><p>El sensor óptico combina detección de proximidad con análisis de color (hue 0-360°, saturación, brillo). Perfecto para contar piezas de colores específicos en el intake.</p><h3>Mapa de Colores (Hue Aproximado)</h3><ul><li>Rojo: hue 0-30 o 330-360</li><li>Amarillo: hue 50-80</li><li>Verde: hue 90-150</li><li>Azul: hue 200-250</li></ul>`,
code:`optical SensorOpt = optical(PORT4);\nvoid detectarColor() {\n    SensorOpt.setLightPower(50, pct); // Activar LED\n    double hue  = SensorOpt.hue();          // 0-360°\n    double sat  = SensorOpt.saturation();   // 0-1.0\n    double bril = SensorOpt.brightness(pct);// 0-100%\n    bool cerca  = SensorOpt.isNearObject(); // proximidad\n    // Identificar color\n    if(cerca) {\n        if(hue < 30 || hue > 330) {\n            Brain.Screen.printAt(10,50,"ROJO detectado!");\n        } else if(hue > 90 && hue < 150) {\n            Brain.Screen.printAt(10,50,"VERDE detectado!");\n        } else if(hue > 200 && hue < 250) {\n            Brain.Screen.printAt(10,50,"AZUL detectado!");\n        }\n    }\n}`,
api_ref:'vex::optical — hue(), saturation(), brightness(pct), isNearObject(), setLightPower()', exercise:'Usa el Optical Sensor para contar cuántas piezas de color específico pasan por tu intake. Muestra el contador en el Brain Screen y en el controlador.'},

{id:48,unit:6,unitTitle:'Sensores VEX V5 Smart Port',title:'Sensor de Rotación — Posición Absoluta',level:'Intermedio',type:'lesson',free:false,duration:30,
desc:'0.1° de resolución para control ultra-preciso de brazos y mecanismos externos.',
theory:`<h3>Specs del Rotation Sensor</h3><table style="width:100%;border-collapse:collapse;font-size:0.9rem"><tr style="border-bottom:1px solid #333"><td><strong>Resolución</strong></td><td>0.1° (3600 posiciones/vuelta)</td></tr><tr style="border-bottom:1px solid #333"><td><strong>Tipo</strong></td><td>Absoluto (recuerda posición al apagar)</td></tr><tr><td><strong>Vs. Motor Encoder</strong></td><td>Externo, no tiene fricción de motor, más preciso para external mechanisms</td></tr></table>`,
code:`rotation SensorRot = rotation(PORT5, false);\nmotor Brazo = motor(PORT2, ratio36_1, false);\n// El rotation sensor da la posición del MECANISMO\n// independientemente del giro interno del motor\nvoid moverBrazoA(double angulo_objetivo) {\n    double Kp = 2.5;\n    double error;\n    do {\n        double actual = SensorRot.angle(degrees);\n        error = angulo_objetivo - actual;\n        // Normalizar -180 a 180\n        while(error >  180) error -= 360;\n        while(error < -180) error += 360;\n        double vel = Kp * error;\n        vel = fmax(-80, fmin(80, vel));\n        Brazo.spin(fwd, vel, pct);\n        wait(10, msec);\n    } while(fabs(error) > 1.0); // tolerancia 1°\n    Brazo.stop(hold);\n}`,
api_ref:'vex::rotation — angle(degrees), position(degrees), velocity(rpm), reversed(bool)', exercise:'Monta el Rotation Sensor en la articulación principal del brazo. Programa 5 posiciones predefinidas (0°, 30°, 60°, 90°, 120°) seleccionables con el controlador.'},

{id:49,unit:6,unitTitle:'Sensores VEX V5 Smart Port',title:'GPS Sensor — Posicionamiento Absoluto de Campo',level:'Avanzado',type:'lesson',free:false,duration:35,
desc:'Conoce tu posición XY exacta en la arena con ±25mm de precisión.',
theory:`<h3>Sistema GPS de VEX</h3><p>La tira GPS en los bordes de la arena emite señales que el sensor procesa para determinar su posición. Da coordenadas absolutas del campo — no relativas al inicio del robot.</p><table style="width:100%;border-collapse:collapse;font-size:0.9rem"><tr style="border-bottom:1px solid #333"><td><strong>Precisión XY</strong></td><td>±25mm en condiciones óptimas</td></tr><tr><td><strong>Requiere</strong></td><td>Tira GPS instalada en el campo</td></tr></table>`,
code:`gps SensorGPS = gps(PORT6);\n// Navegar a una posición absoluta del campo\nvoid navegarAPos(double target_x, double target_y) {\n    while(true) {\n        double x = SensorGPS.xPosition(mm);\n        double y = SensorGPS.yPosition(mm);\n        double heading = SensorGPS.heading(degrees);\n        double dx = target_x - x;\n        double dy = target_y - y;\n        double dist = sqrt(dx*dx + dy*dy);\n        if(dist < 25) break; // llegó (tolerancia ±25mm)\n        // Calcular ángulo hacia el objetivo\n        double angulo_target = atan2(dy, dx) * 180.0 / M_PI;\n        // Girar hacia el objetivo\n        girarA(angulo_target, 50); // función PID con IMU\n        // Avanzar un poco\n        avanzarRecto(fmin(dist/10.0, 20), 60);\n    }\n}`,
api_ref:'vex::gps — xPosition(mm), yPosition(mm), heading(degrees), quality()', exercise:'Usa el GPS para hacer que el robot regrese al centro exacto del campo (0,0) independientemente de dónde empezó. Mide el error de llegada en X e Y.'},

{id:50,unit:6,unitTitle:'Sensores VEX V5 Smart Port',title:'Fusión de Sensores — IMU + GPS + Encoders',level:'Experto',type:'lesson',free:false,duration:50,
desc:'Combina múltiples sensores para localización robusta en condiciones reales de torneo.',
theory:`<h3>El Problema de Sensor Único</h3><p>Ningún sensor es perfecto en condiciones de torneo. La luz del venue afecta al Vision Sensor, la deriva acumula error en la odometría, el GPS puede perder la señal en ciertas posiciones.</p><h3>Fusión de Sensores</h3><p>La solución profesional: usar múltiples fuentes de datos y priorizar según confiabilidad. Un filtro de Kalman básico puede combinar GPS (baja frecuencia, alta precisión) con odometría (alta frecuencia, deriva acumulada).</p>`,
code:`// Estimación de posición fusionada: GPS + Odometría\nstruct Pose { double x, y, theta; };\nPose poseEstimada = {0, 0, 0};\nPose poseOdometria = {0, 0, 0};\n// Factor de confianza: 0=solo odometría, 1=solo GPS\nconst double GPS_TRUST = 0.7;\nvoid fusionarSensores() {\n    // Actualizar odometría\n    actualizarOdometria(poseOdometria); // tu función\n    // Si GPS disponible y con buena calidad\n    if(SensorGPS.quality() > 90) {\n        Pose poseGPS = {\n            SensorGPS.xPosition(mm),\n            SensorGPS.yPosition(mm),\n            SensorGPS.heading(degrees)\n        };\n        // Fusión ponderada\n        poseEstimada.x = GPS_TRUST*poseGPS.x + (1-GPS_TRUST)*poseOdometria.x;\n        poseEstimada.y = GPS_TRUST*poseGPS.y + (1-GPS_TRUST)*poseOdometria.y;\n        poseEstimada.theta = Imu.heading(degrees); // IMU siempre para theta\n    } else {\n        poseEstimada = poseOdometria; // solo odometría si GPS no disponible\n    }\n}`,
api_ref:'vex::gps — quality() | vex::inertial — heading() | Algoritmo Fusión de Sensores', exercise:'Implementa la fusión GPS+IMU. Compara la localización fusionada vs. solo odometría en 5 pruebas. Documenta la reducción de error en mm.'},

{id:51,unit:6,unitTitle:'Sensores VEX V5 Smart Port',title:'potentiometerV2 — Control Angular de Precisión',level:'Intermedio',type:'lesson',free:false,duration:25,
desc:'El potenciómetro inteligente para posicionamiento absoluto de mecanismos.',
theory:`<h3>potentiometerV2 vs Rotation Sensor</h3><p>El potenciómetro V2 es un Smart Port que mide ángulo de 0° a 250°. El Rotation Sensor mide rotación completa continua. Elige según tu mecanismo:</p><ul><li>Rango &lt; 250°: potentiometerV2 (más simple)</li><li>Rango completo (360° o más): Rotation Sensor</li></ul>`,
code:`potentiometerV2 Pot = potentiometerV2(PORT9);\n// El potenciómetro da ángulo absoluto sin resetear\ndouble angulo = Pot.angle(degrees);    // 0-250°\ndouble angRad = Pot.angle(radians);\ndouble vel    = Pot.velocity(rpm);     // velocidad\n// Control de posición con potenciómetro\nvoid mantenerPosicion(double objetivo) {\n    double Kp = 3.0;\n    while(true) {\n        double error = objetivo - Pot.angle(degrees);\n        Brazo.spin(fwd, Kp * error, pct);\n        if(fabs(error) < 1.0) { Brazo.stop(hold); break; }\n        wait(10, msec);\n    }\n}`,
api_ref:'vex::potentiometerV2 — angle(degrees), angle(radians), velocity(rpm)', exercise:'Usa el potenciometerV2 para saber el ángulo exacto de tu brazo en todo momento. Calibra 5 posiciones (home, bajo, medio, alto, máximo) y actívalas con botones.'},

{id:52,unit:6,unitTitle:'Sensores VEX V5 Smart Port',title:'lightV2 — Sensor de Luz Inteligente',level:'Básico',type:'lesson',free:false,duration:20,
desc:'Detecta intensidad lumínica y colores básicos con el Light Sensor V2.',
theory:`<h3>Light Sensor V2</h3><p>El sensor de luz V2 es un Smart Port que mide luminosidad ambiental. Útil para:</p><ul><li>Detectar cuando el robot está bajo una estructura</li><li>Line following básico con umbral de brillo</li><li>Confirmar que el LED del Vision Sensor está encendido</li></ul>`,
code:`lightV2 SensorLuz = lightV2(PORT10);\nvoid detectarLuz() {\n    double nivel_pct = SensorLuz.brightness(pct); // 0-100%\n    bool iluminado   = nivel_pct > 50;\n    Brain.Screen.printAt(10,50,\n        "Luz: %.0f%% - %s",\n        nivel_pct, iluminado?"Iluminado":"Oscuro");\n    // Ejemplo: detectar si el robot está bajo una rampa\n    if(nivel_pct < 20) {\n        Brain.Screen.printAt(10,80,"Robot bajo estructura!");\n    }\n}`,
api_ref:'vex::lightV2 — brightness(pct), isNearObject()', exercise:'Usa el sensor de luz para detectar si el robot está en zona sombreada del campo. Programa que reduzca velocidad al 60% en zonas oscuras (por ejemplo debajo de una plataforma elevada).'},

{id:53,unit:6,unitTitle:'Sensores VEX V5 Smart Port',title:'Examen Unidad 6 — Sensores Smart Port',level:'Intermedio',type:'exam',free:false,duration:20,
desc:'Certifica tu dominio de los 8 sensores del puerto inteligente VEX V5.',exam:[
{q:'¿Cuántas firmas de color simultáneas soporta el Vision Sensor?',options:['3','5','7','10'],correct:2},
{q:'¿Cuál es la resolución del Rotation Sensor?',options:['1°','0.5°','0.1°','0.01°'],correct:2},
{q:'La precisión del GPS Sensor en condiciones óptimas es:',options:['±5mm','±25mm','±50mm','±100mm'],correct:1},
{q:'¿Qué función del IMU da el ángulo ACUMULADO (puede ser >360°)?',options:['heading()','rotation()','yaw()','pitch()'],correct:1},
{q:'El Optical Sensor usa hue() para detectar color. El rojo tiene hue aproximado de:',options:['100-150°','200-250°','0-30° o 330-360°','50-80°'],correct:2},
{q:'¿Para qué se recomienda principalmente objectVelocity() del Distance Sensor?',options:['Velocidad del motor','Velocidad de acercamiento del objeto detectado','Velocidad del robot','Tasa de actualización del sensor'],correct:1},
],code:'',api_ref:''},

// Mod 54-75 continúan...
{id:54,unit:6,unitTitle:'Sensores VEX V5 Smart Port',title:'AI Vision Sensor — Inteligencia Artificial',level:'Experto',type:'lesson',free:false,duration:50,
desc:'El sensor de visión con IA a bordo detecta objetos sin importar la iluminación del venue.',
theory:`<h3>AI Vision vs Vision Sensor</h3><p>El Vision Sensor clasifica por color (sensible a luz). El <strong>AI Vision Sensor</strong> usa una red neuronal entrenada a bordo para clasificar objetos por forma independientemente de la iluminación.</p><h3>Modos</h3><ul><li><strong>Color signaturas</strong>: igual al Vision Sensor</li><li><strong>Color code</strong>: multi-color patterns</li><li><strong>Tag detection</strong>: AprilTags (balizas)</li><li><strong>Object detection</strong>: modelos entrenados</li></ul>`,
code:`aiVision SensorAI = aiVision(PORT8);\n// Detección por tag (AprilTag) — muy robusta en torneos\nvoid detectarTag() {\n    SensorAI.takeSnapshot(aiVision::ALL_TAGS);\n    for(int i = 0; i < SensorAI.objectCount; i++) {\n        aiVision::object obj = SensorAI.objects[i];\n        int tagId  = obj.classID; // ID del AprilTag\n        int cx     = obj.centerX; // posición en la imagen\n        int cy     = obj.centerY;\n        int width  = obj.width;\n        Brain.Screen.printAt(10, 50+i*30,\n            "Tag %d en X:%d Y:%d W:%d", tagId, cx, cy, width);\n    }\n}`,
api_ref:'vex::aiVision — takeSnapshot(mode), objectCount, objects[].classID/centerX/centerY', exercise:'Configura el AI Vision Sensor con AprilTags en diferentes metas de tu campo. Programa el robot para identificar cuál baliza está más cerca y navegar hacia ella.'},
];
